### ISSUE TITLE
Component shows up tiny, images don't seem to load?

### ISSUE THREAD

**Issue by gulkily** [BarishNamazov/image-compare#1]
I'm having an issue where the component appears very small, see screenshot

<img width="1225" alt="Screen Shot 2022-05-06 at 1 29 30 PM" src="https://user-images.githubusercontent.com/1530699/167182868-a8d019e8-de9d-43c2-87a0-bfc7866d1a1b.png">

Here is my code, and I've checked that the images are accessible:

`<html>`
`	<script type="module" src="https://barishnamazov.github.io/image-compare/src/index.js"></script>`
`	<body>`
`		<image-compare direction="vertical">`
`			<img src="./examples/lilypads.jpeg" slot="image-1">`
`  			<img src="./examples/hydrangea.jpeg" slot="image-2">`
`		</image-compare>`
`	</body>`
`</html>`

**Comment by BarishNamazov** [comment]
Please use correct image sources and try again. The example images are in my repo website, so you can use e.g.: https://barishnamazov.github.io/image-compare/examples/lilypads.jpeg

**Comment by gulkily** [comment]
Thanks for your help! The issue was that I have image loading turned off by default in my browser :)

**Comment by gulkily** [comment]
I've been thinking about this issue some more, and I think there may still opportunity for an enhancement here?

When the resulting image is 0x0, perhaps something should be output in the console to let the developer know what the cause of the unexpected component appearance is?
